// Code generated by MockGen. DO NOT EDIT.
// Source: cat-api/breed/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "cat-api/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBreedByName mocks base method
func (m *MockService) GetBreedByName(breedName string) (*models.Breed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBreedByName", breedName)
	ret0, _ := ret[0].(*models.Breed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBreedByName indicates an expected call of GetBreedByName
func (mr *MockServiceMockRecorder) GetBreedByName(breedName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBreedByName", reflect.TypeOf((*MockService)(nil).GetBreedByName), breedName)
}
