USE cats;
CREATE TABLE
IF NOT EXISTS breeds
(
  id VARCHAR
(4) PRIMARY KEY NOT NULL,
  attributes JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;

CREATE TABLE
IF NOT EXISTS users
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR
(255) NOT NULL,
  pass VARCHAR
(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;

INSERT INTO cats.users
    (username, pass)
VALUES("admin", SHA1("@#$RF@!718"));